FROM node:18-bookworm-slim as transpiled_service
WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-bookworm-slim as service_dependencies
WORKDIR /usr/app
COPY package*.json ./
RUN npm install --omit=dev

FROM node:18-bookworm-slim as final
WORKDIR /opt
COPY --from=transpiled_service /usr/app/dist/ ./
COPY --from=service_dependencies /usr/app/node_modules ./node_modules
EXPOSE 8080

CMD [ "node", "./handlers/download-queued-market-orders.js"]