build.service.download_queued_market_orders:
	docker build . -f ./docker/Dockerfile.download_queued_market_orders  -t gzeller/eve-download-queued-market-orders:$(TAG)

build.service.queue_market_orders_for_download:
	docker build . -f ./docker/Dockerfile.queue_market_orders_for_download  -t gzeller/eve-queue-market-orders-for-download:$(TAG)